[package]
name = "talaria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
qmetaobject = { version = "0.2.7", features = ["webengine"] }
cstr = "0.2.10"
cpp = "0.5.6"
